### ISSUE TITLE
Unable to install module

### ISSUE THREAD

**Issue by ChristianGiupponi** [daylightstudio/FUEL-CMS-Backup-Module#2]
Hi,
I'm new in fuelcms and I tried to install this module following the "Manual installation" but when I run:

```
php index.php fuel/installer/install/ backup
```

I get:

```
<div id="error_db">
    <h1>A Database Error Occurred</h1>
    <p>Unable to connect to your database server using the provided settings.</p><p>Filename: /Users/christiangiupponi/vagrant/stilogo/www/fuelcms/fuel/modules/fuel/core/Loader.php</p><p>Line Number: 136</p></div>
```

But I'm able to log into the admin area, I have set all the parameters in the database.php file, there are other configuration for the DB login?

**Comment by bobbaker404** [comment]
Just a note for others ... if using XAMPP the correct way to run this is:
`/Applications/XAMPP/bin/php index.php fuel/installer/install/ backup`
